# Generated by Django 2.2.16 on 2022-05-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='5!nxasv!zd39x8y+^w!9%gg)jdzuap2l&o+h3q37#1s%+y8sa^', max_length=64, verbose_name='Код подтверждения'),
        ),
    ]
